### ISSUE TITLE
Cannot get paths with a $ sign in the path to work

### ISSUE THREAD

**Issue by ahenket** [eeditiones/oas-router#1]
[api.json.txt](https://github.com/eeditiones/oas-router/files/5590506/api.json.txt)

When I have a definition with a dollar in the path to signal an operation on an object, the openas-router fails to match my path:

```json
"/issues/$list": {
    "get": {
        "operationId": "isapi:getIssueList",
        "summary": "Retrieves DECOR issue list",
        "responses": {
            "200": {
                "content": {
                    "application/json": {},
                    "application/xml": {},
                    "text/json": {}
                },
                "description": "issue structure including generated meta data"
            }
        },
        "tags": ["isapi"]
    }
}
```

**Comment by JoernT** [comment]
@ahenket really strange - i did a quick test in the tei-publisher api adding a '/$foo' to the path and it actually worked. Guess you had more pathes with '/issues' - maybe a combination of things here - can you please send your api.json file (or just the relevant section of pathes).

**Comment by ahenket** [comment]
@JoernT I've attached the api.json to the original question.

**Comment by JoernT** [comment]
@ahenket that was too obvious ;)

**Comment by JoernT** [comment]
i can confirm at least that GET and POST requests are different. The issue seems to come with GET request while POST calls the defined operationId as expected
