### ISSUE TITLE
Recommendations for responding to different Accept headers

### ISSUE THREAD

**Issue by ahenket** [eeditiones/oas-router#2]
Currently my OpenAPI spec allows for json/xml/html to be returned.

1. What is the best way to inspect what the Accept header of the request is?

2. How do I instructor my response to be xml? This code is not working and returns text/plain instead:

```xquery
response:set-header('Content-Type', 'text/xml; charset=utf-8'), json-to-xml($echo)
```

We would love to see some more documentation on this common pattern.

**Comment by wolfgangmm** [comment]
We use the following procedure to determine the response type:

1. your XQuery handler function may directly set the response type by calling e.g. `router:response(200, "text/html", $content)`
2. otherwise, the router tries to select one of the response types defined in you OpenAPI specs:
    * checking the Content-Type header of the request: if it is set and corresponds to one of the types defined in the spec, it is used
    * fall back to the first response type defined for the given response code (e.g. "200") or code marked as "default"

We'll add more specific tests to illustrate this. Currently all the tests are part of TEI Publisher, but we should have a test suite in this package as well, so we can test the various edge cases.

**Comment by ahenket** [comment]
I've replace my one liner above to:

```xquery
    response:set-header('Content-Type', 'application/xml; charset=utf-8'),
    router:response(200, "application/xml", json-to-xml($echo))
```

And that works for xml. But for json I still get something serialized as a string:

```xquery
    response:set-header('Content-Type', 'application/json; charset=utf-8'), 
    router:response(200, "application/json", $echo)
```

output

```text
"{\n  \"body\" : null,\n  \"config\" : {\n    \"config\" : {\n      \"operationId\" : \"testapi:echo\",\n      \"summary\" : \"Just echo back what was sent in. Request body, parameters, headers, and more\",\n      \"responses\" : {\n        \"200\" : {\n          \"content\" : {\n            \"application/json\" : { },\n            \"text/html\" : { },\n            \"text/xml\" : { },\n            \"application/xml\" : { }\n          },\n          \"description\" : \"html, json or xml version of the output\"\n        }\n      },\n      \"tags\" : [ \"testapi\" ]\n    },\n...
```

The relevant part of the api.json:

```json
    "/echo": {
        "get": {
            "operationId": "testapi:echo",
            "summary": "Just echo back what was sent in. Request body, parameters, headers, and more",
            "responses": {
                "200": {
                    "content": {
                        "application/json": {},
                        "application/xml": {},
                        "text/xml": {},
                        "text/html": {}
                    },
                    "description": "html, json or xml version of the output"
                }
            },
            "tags": ["testapi"]
        }
    }
```

**Comment by ahenket** [comment]
Hang on ... found my own answer ... the contents of ```$echo``` actually was a string:

```xquery
let $echo   := fn:serialize($request, map{'method':'json', 'indent': true(), 'json-ignore-whitespace-text-nodes':'yes'})
```

is not json yet. This does the trick:
```
let $echo   := fn:serialize($request, map{'method':'json', 'indent': true(), 'json-ignore-whitespace-text-nodes':'yes'})
let $echo   := parse-json($echo)
```

**Comment by wolfgangmm** [comment]
While it does not do any harm, I think it is best to not use `response:set-header` but leave it to the router to set the header.

**Comment by ahenket** [comment]
The idea is to make the charset explicit this way. Is there a different way? E.g.:

```xquery
router:response(200, "application/json; charset=utf-8", $echo)
```
